slider/blog/urls.py
from django.urls import path
from .views import blog
from .views import category
from .views import post

app_name = 'blog'

urlpatterns = [
    path('', blog, name='blog'),
    path('/<slug:category>', category, name='category'),
    path('/<slug:category>/<slug:post>', post, name='post'),
]

slider/docs/urls.py
from django.urls import path
from .views import docs_index
from .views import docs_article

app_name = 'docs'

urlpatterns = [
    path('', docs_index, name='docs-index'),
    path('/<slug:docs_article>', docs_article, name='docs-article'),
]

slider/slider/urls.py
from django.contrib import admin
from django.urls import path
from home.views import home
from about.views import about
from docs.views import docs_index
from contacts.views import contacts

from django.urls import include


urlpatterns = [
    path('', home, name='home'),
    path('about', about, name='about'),
    path('docs', include('docs.urls')),
    path('blog', include('blog.urls')),
    path('contacts', contacts, name='contacts'),
    path('admin', admin.site.urls),
]

slider/blog/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=32, unique=True)
    category_slug = models.SlugField(max_length=128, unique=True, null=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=256, null=True)
    description = models.TextField(null=True)
    text = models.TextField(null=True)
    img_preview = models.CharField(max_length=256, null=True)
    img_article = models.CharField(max_length=256, null=True)
    post_slug = models.SlugField(max_length=128, unique=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.RESTRICT, null=True)

slider/docs/models.py
from django.db import models

class DocsLink(models.Model):
    name = models.CharField(max_length=32, unique=True)
    docs_slug = models.SlugField(max_length=128, unique=True, null=True)


class DocsArticle(models.Model):
    title = models.CharField(max_length=256, null=True)
    text = models.TextField(null=True)
    docs_category = models.OneToOneField(
        DocsLink, 
        on_delete=models.CASCADE,
        primary_key=True
    )

slider/pages/models.py
from django.db import models

class Page(models.Model):
    title = models.CharField(max_length=32)
    text = models.TextField(null=True)

slider/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass

slider/about/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from pages.models import Page

def about(request: HttpRequest) -> HttpResponse:
    about_page = Page.objects.get(pk=1)

    context = {
        'about': about_page
    }
    
    return render(request, 'about/about.html', context)

slider/blog/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse

from .models import Category
from .models import Post


def blog(request: HttpRequest) -> HttpResponse:
    categories = Category.objects.all()
    posts = Post.objects.all()
    
    context = {
        'categories': categories,
        'posts': posts
    }

    return render(request, 'blog/blog.html', context=context)


def category(request: HttpRequest, category) -> HttpResponse:    
    categories = Category.objects.all()
    posts = Post.objects.filter(category_id__category_slug=category)

    context = {
        'categories': categories,
        'posts': posts
    }

    return render(request, 'blog/category.html', context)


def post(request: HttpRequest, category, post) -> HttpResponse:
    categories = Category.objects.all()
    post = Post.objects.filter(category_id__category_slug=category, post_slug=post)

    context = {
        'categories': categories,
        'post': post
    }

    return render(request, 'blog/post.html', context)

slider/contacts/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse

def contacts(request: HttpRequest) -> HttpResponse:
    return render(request, 'contacts/contacts.html')

slider/docs/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse

from pages.models import Page

from .models import DocsLink
from .models import DocsArticle

def docs_index(request: HttpRequest) -> HttpResponse:
    docs_links = DocsLink.objects.all()
    docs_page = Page.objects.get(pk=2)

    context = {
        'docs': docs_page,
        'links': docs_links,
    }

    return render(request, 'docs/docs.html', context)


def docs_article(request: HttpRequest, docs_article) -> HttpResponse:
    docs_links = DocsLink.objects.all()
    docs_article = DocsArticle.objects.get(docs_category__docs_slug=docs_article)

    context = {
        'docs': docs_article,
        'links': docs_links,
    }

    return render(request, 'docs/docs-article.html', context)

slider/home/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse

def home(request: HttpRequest) -> HttpResponse:
    return render(request, 'home/home.html')

slider/pages/views.py
from django.shortcuts import render

# Create your views here.

slider/templates/about/about.html
{% extends 'base.html' %}

{% block title %}
About
{% endblock %}

{% block content%}
            <div class="about p">
                <div class="container">
                    <main class="main">
                        <article class="article">
                            {{ about.text|safe }}
                        </article>
                    </main>
                </div>
            </div>
{% endblock%}

slider/templates/blog/blog.html
{% extends 'base.html' %}

{% block title %}
Blog
{% endblock %}

{% block content%}

            {% load static %}
            <div class="all-blog-posts g">
                <div class="container">
                    <div class="page-block--title">All posts</div>

                    <ul class="all-blog-posts--previews">
                        {% for post in posts %}
                        <li>
                            <div class="all-blog-posts--preview">
                                <div class="c1">
                                    <img class="all-blog-posts--img" src="{{ post.img_preview }}" alt="">
                                </div>

                                <div class="c2">
                                    <div class="all-blog-posts--article">
                                        <div class="category">
                                            <a href="/blog/{{ post.category.category_slug }}" class="category-link">
                                                {{ post.category.name }}
                                            </a>
                                        </div>

                                        <div class="title">
                                            <a href="{% url 'blog:post' post.category.category_slug post.post_slug %}"
                                                class="post-link">
                                                <h2>{{ post.title }}</h2>
                                            </a>
                                        </div>

                                        <div class="text">
                                            <p>{{ post.description }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
{% endblock%}

slider/templates/blog/category.html
{% extends 'base.html' %}

{% block title %}
Blog Category
{% endblock %}

{% block content%}

            {% load static %}
            <div class="blog-category g">
                <div class="container">
                    <div class="two-columns">
                        <main class="main">
                            <ul class="blog-category-previews">
                                {% for post in posts %}
                                <li>
                                    <div class="blog-category-preview">
                                        <div class="c1">
                                            <img class="blog-category--img" src="{{ post.img_preview }}" alt="">
                                        </div>

                                        <div class="c2">
                                            <div class="blog-category--article">
                                                <div class="title">
                                                    <a href="{% url 'blog:post' post.category.category_slug post.post_slug %}" class="post-link">
                                                        <h2>{{ post.title }}</h2>
                                                    </a>
                                                </div>

                                                <div class="text">
                                                    <p>{{ post.description }}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                {% endfor %}
                            </ul>
                        </main>

                        <aside class="aside">
                            <ul class="aside-blocks">
                                <li>
                                    <div class="aside-block">
                                        <div class="aside-block--title">Categories</div>

                                        <nav class="aside-nav">
                                            <ul class="aside-menu">
                                                {% for category in categories %}
                                                <li class="item">
                                                    <a href="{% url 'blog:category' category.category_slug %}" class="link">
                                                        <div class="aside-menu--item">{{ category.name }}</div>
                                                    </a>
                                                </li>
                                                {% endfor %}
                                            </ul>
                                        </nav>
                                    </div>
                                </li>
                            </ul>
                        </aside>
                    </div>
                </div>
            </div>
{% endblock%}

slider/templates/blog/post.html
{% extends 'base.html' %}

{% block title %}
Blog Post
{% endblock %}

{% block content%}

            {% load static %}
            <main class="blog-post">
                <article class="article">
                    <section class="blog-post--title p">
                        <div class="container">
                            {% for p in post %}
                            <h1>{{ p.title }}</h1>
                            {% endfor %}

                            <div class="blog-post--category">
                                {% for p in post %}
                                <div>{{ p.category.name }}</div>
                                {% endfor %}
                            </div>
                        </div>
                    </section>

                    <figure class="blog-post--figure">
                        <img src="{% for p in post %} {{ p.img_article }} {% endfor %}" alt="" class="img">
                    </figure>

                    <section class="blog-post--text p">
                        <div class="container">
                            {% for p in post %}
                                <div>{{ p.text|safe }}</div>
                            {% endfor %}
                        </div>
                    </section>
                </article>
            </main>
{% endblock%}

slider/templates/contacts/contacts.html
{% extends 'base.html' %}

{% block title %}
Contacts
{% endblock %}

{% block content%}
            <div class="contacts-page">
                <div class="container">
                    <div class="contacts-titles">
                        <div class="page-title">Contact us</div>

                        <h1>Let's Start a Conversation</h1>

                        <div class="description">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
                                et dolore magna aliqua. Ut enim ad minim.</p>
                        </div>
                    </div>

                    <div class="contacts">
                        <div class="container">
                            <div class="c1">
                                <div class="contacts-title">Working hours</div>

                                <ul class="contacts-list">
                                    <li>
                                        <div class="contacts-list--item">Monday To Friday</div>
                                    </li>

                                    <li>
                                        <div class="contacts-list--item">9:00 AM to 8:00 PM</div>
                                    </li>

                                    <li>
                                        <div class="contacts-list--item">EET</div>
                                    </li>
                                </ul>
                            </div>

                            <div class="c2">
                                <div class="contacts-title">Contacts Us</div>

                                <ul class="contacts-list">
                                    <li>
                                        <div class="contacts-list--item">slider@vmdev.space</div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <form id="cf" action="" class="contacts-form">
                        <div class="form">
                            <div class="contacts-form-fields">
                                <div class="field">
                                    <div class="contacts-form--field">
                                        <input type="text" class="input" placeholder="Name">
                                        <div class="error">error</div>
                                    </div>
                                </div>

                                <div class="field">
                                    <div class="contacts-form--field">
                                        <input type="text" class="input" placeholder="Email">
                                        <div class="error">error</div>
                                    </div>
                                </div>

                                <div class="field">
                                    <div class="contacts-form--field">
                                        <textarea name="" id="" class="textarea" placeholder="Message"></textarea>
                                        <div class="error">error</div>
                                    </div>
                                </div>
                            </div>

                            <div class="submit">
                                <input type="submit" class="contacts-form--submit" value="Send Message">
                            </div>
                        </div>

                        <!-- preloader -->
                        <!-- classList: d a -->
                        <!-- display: block | opacity: 1 -->
                        <div class="form-preloader-overlay">
                            <div class="form-preloader">
                                <div class="container">
                                    <ul class="preloader-modes">

                                        <!-- classList: on -->
                                        <!-- display: block -->
                                        <li class="mode sending on">
                                            <div class="preloader-mode">
                                                <div class="loadingio-spinner-spinner-go6ip63iaz">
                                                    <div class="ldio-m9d4numlatn">
                                                        <div></div>
                                                        <div></div>
                                                        <div></div>
                                                        <div></div>
                                                        <div></div>
                                                        <div></div>
                                                        <div></div>
                                                        <div></div>
                                                        <div></div>
                                                        <div></div>
                                                        <div></div>
                                                        <div></div>
                                                        <div></div>
                                                        <div></div>
                                                        <div></div>
                                                        <div></div>
                                                        <div></div>
                                                        <div></div>
                                                        <div></div>
                                                        <div></div>
                                                        <div></div>
                                                        <div></div>
                                                        <div></div>
                                                        <div></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>

                                        <li class="mode success">
                                            <div class="preloader-mode">
                                                <div class="title">Success!</div>

                                                <div class="message">
                                                    <p>The subscribe request has sent</p>
                                                    <p>Check your email and confirm your subscription</p>
                                                </div>

                                                <div class="close">
                                                    <button>Close</button>
                                                </div>
                                            </div>
                                        </li>

                                        <li class="mode error">
                                            <div class="preloader-mode">
                                                <div class="title">Error!</div>

                                                <div class="message">
                                                    <p>Looks like server error!</p>
                                                </div>

                                                <div class="link">
                                                    <div class="preload-mode--link">
                                                        <span class="t">Visit <a href="" class="">Contacts</a> page</span>
                                                    </div>
                                                </div>

                                                <div class="close">
                                                    <button>Close</button>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!-- end preloader -->
                    </form>
                </div>
            </div>
{% endblock%}

slider/templates/docs/docs-article.html
{% extends 'base.html' %}

{% block title %}
Docs
{% endblock %}

{% block content%}
            <div class="docs g">
                <div class="container">
                    <div class="two-columns">
                        <main class="main">
                            <article class="article">
                                {{ docs.text|safe }}
                            </article>
                        </main>

                        <aside class="aside">
                            <ul class="aside-blocks">
                                <li>
                                    <div class="aside-block">
                                        <div class="aside-block--title">Documentation</div>

                                        <nav class="aside-nav">
                                            <ul class="aside-menu">
                                                {% for link in links%}
                                                <li class="item">
                                                    <a href="/docs/{{ link.docs_slug }}" class="link">
                                                        <div class="aside-menu--item">{{ link.name }}</div>
                                                    </a>
                                                </li>
                                                {% endfor %}
                                            </ul>
                                        </nav>
                                    </div>
                                </li>
                            </ul>
                        </aside>
                    </div>
                </div>
            </div>
{% endblock%}

slider/templates/docs/docs.html
{% extends 'base.html' %}

{% block title %}
Docs
{% endblock %}

{% block content%}
            <div class="docs g">
                <div class="container">
                    <div class="two-columns">
                        <main class="main">
                            <article class="article">
                                <h1>Installation</h1>

                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                                    labore et
                                    dolore magna aliqua. Non blandit massa enim nec. Scelerisque viverra mauris in aliquam sem. At
                                    risus
                                    viverra adipiscing at in tellus. Sociis natoque penatibus et magnis dis parturient montes.
                                    Ridiculus mus
                                    mauris vitae ultricies leo. Neque egestas congue quisque egestas diam. Risus in hendrerit
                                    gravida rutrum
                                    quisque non.</p>

                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                                    labore et
                                    dolore magna aliqua. Non blandit massa enim nec. Scelerisque viverra mauris in aliquam sem. At
                                    risus
                                    viverra adipiscing at in tellus. Sociis natoque penatibus et magnis dis parturient montes.
                                    Ridiculus mus
                                    mauris vitae ultricies leo. Neque egestas congue quisque egestas diam. Risus in hendrerit
                                    gravida rutrum
                                    quisque non.</p>

                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                                    labore et
                                    dolore magna aliqua. Non blandit massa enim nec. Scelerisque viverra mauris in aliquam sem. At
                                    risus
                                    viverra adipiscing at in tellus. Sociis natoque penatibus et magnis dis parturient montes.
                                    Ridiculus mus
                                    mauris vitae ultricies leo. Neque egestas congue quisque egestas diam. Risus in hendrerit
                                    gravida rutrum
                                    quisque non.</p>
                            </article>
                        </main>

                        <aside class="aside">
                            <ul class="aside-blocks">
                                <li>
                                    <div class="aside-block">
                                        <div class="aside-block--title">Documentation</div>

                                        <nav class="aside-nav">
                                            <ul class="aside-menu">
                                                <li class="item">
                                                    <a href="" class="link active">
                                                        <div class="aside-menu--item">Installation</div>
                                                    </a>
                                                </li>

                                                <li class="item">
                                                    <a href="" class="link">
                                                        <div class="aside-menu--item">Configuration</div>
                                                    </a>
                                                </li>
                                            </ul>
                                        </nav>
                                    </div>
                                </li>
                            </ul>
                        </aside>
                    </div>
                </div>
            </div>
{% endblock%}

slider/templates/documentation/documentation.html
{% extends 'base.html' %}

{% block title %}
    Documentation
{% endblock %}

{% block content%}
    documentation.html
{% endblock%} 